name: Build and deploy ASP.Net Core app to Azure Web App - SQLLab

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet publish -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_36B81F26E3D847119082D41C519584DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03FF2C03E4F946A7BA8FFE9B3D4845C9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_848424281AD947519FC5C1A796029AF9 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: SQLLab
          package: publish